from .dairy_resource import DairyResource
from .contacts_resource import ContactsResource
from .rent_resource import RentResource
from .booking_resource import BookingResource
from .services_resource import ServiceResource
from .add_event_resource import AddEventResource
from .events_resource import EventsResource
from .get_booking_resource import GetBookingResource
from .delete_booking_resource import DeleteBookingResource
